/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type BikeSales = {
    /**
     * Name of the bike model
     */
    bike_model: string;
    /**
     * Date of the sale
     */
    order_date: string;
    /**
     * Total number of bikes sold
     */
    total_sales: number;
    /**
     * Total revenue generated by this model
     */
    revenue: number;
};

