openapi: 3.0.3
info:
  title: Customer API
  version: 1.0.0
  description: API for managing customer data
servers:
  - url: https://api.example.com

paths:
  /customers:
    get:
      summary: Retrieve a list of customers
      operationId: getCustomers
      parameters:
        - $ref: "#/components/parameters/FilterParam"
      responses:
        '200':
          description: A list of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        '401':
          description: Unauthorized – missing or invalid token
        '403':
          description: Forbidden – insufficient permissions for projects
        '500':
          description: Internal server error
      tags:
        - Customers
    delete:
      summary: Delete a customer by ID
      operationId: deleteCustomer
      parameters:
        - $ref: "#/components/parameters/IdParam"
        - $ref: "#/components/parameters/CascadeParam"
      responses:
        '204':
          description: Customer deleted successfully
        '409':
          description: Conflict – related data exists; use cascade=true to force delete
        '400':
          description: Bad request – missing or invalid ID
        '401':
          description: Unauthorized – missing or invalid token
        '500':
          description: Internal server error
      tags:
        - Customers
    put:
      summary: Update a customer
      operationId: updateCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Customer updated successfully
        '400':
          description: Bad request – missing or invalid fields
        '401':
          description: Unauthorized – missing or invalid token
        '404':
          description: Customer not found
        '500':
          description: Internal server error
      tags:
        - Customers
    post:
      summary: Create a new customer
      operationId: createCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '201':
          description: Customer created successfully
        '400':
          description: Bad request – missing or invalid fields
        '401':
          description: Unauthorized – missing or invalid token
        '409':
          description: Conflict – duplicate or invalid data
        '500':
          description: Internal server error
      tags:
        - Customers

components:
  parameters:
    FilterParam:
      name: filter
      in: query
      description: Query filter string, e.g. project_id:$eq.1|2|3
      required: false
      schema:
        type: string

    IdParam:
      name: id
      in: query
      description: ID of the customer to delete
      required: true
      schema:
        type: integer
        example: 123

    CascadeParam:
      name: cascade
      in: query
      description: Whether to delete related data as well
      required: false
      schema:
        type: boolean
        example: true

  schemas:
    Customer:
      type: object
      required: [ email, password, first_name, name, dob, city, project_id ]
      properties:
        id:
          type: integer
          description: Unique identifier for the customer
        email:
          type: string
          description: Customer's email address
        password:
          type: string
          description: Hashed password for authentication
        first_name:
          type: string
          description: Customer's given name
        name:
          type: string
          description: Customer's family name
        dob:
          type: string
          format: date
          description: Date of birth (YYYY-MM-DD)
        city:
          type: string
          description: City of residence
        project_id:
          type: integer
          description: Project ID associated with the customer
